chore(3.3.3-sp): dependencies check
googleapis/java-spanner pull request #1224
Opened 2021-05-31 03:06 UTC by thiagotnunes

We had to do a couple of things in this PR:

1. We used the versions as specified 
https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/boms/cloud-lts-bom/pom.xml
2. We had to remove the dependency on google-cloud-shared-dependencies
3. There were some versions which were not specified in the above POM and we had to "guess" the best version taking in account maven build enforcer (which checks for transitive dependency version compatibilities).
4. We had compilation errors in the main and test code in regards to the google guava Predicate class. We had to implement the `test` method in addition to the `apply` method, since we are using Java 7 here and can not rely on `default` interface method definitions.

2021-05-31 03:14 UTC, thiagotnunes commented on pom.xml
> +
The dependencies below this line are the ones we had to "guess" and fix based on errors of the maven build enforcer checks (for transitive versions compatibilities). These would usually come from the google-cloud-shared-libraries, but we did not know which version of those to use.

@elharo Is this the approach we would like to take or will we release a version of the google-cloud-shared-libraries that is compatible with the lts versions of all the libraries we have?

2021-05-31 03:14 UTC, thiagotnunes commented on pom.xml
> +<!--      <dependency>-->
@elharo we had to remove the google-cloud-shared-dependencies, since some versions did not work with our build.

2021-05-31 03:14 UTC, thiagotnunes commented on pom.xml
> +        <groupId>com.google.errorprone</groupId>
We had to manually add `errorprone`

2021-05-31 03:14 UTC, thiagotnunes commented on pom.xml
> +        <groupId>io.grpc</groupId>
We had to manually add `grpc-netty-shaded`

2021-05-31 03:14 UTC, thiagotnunes commented on pom.xml
> +        <version>4.13.2</version>
We had to upgrade `junit`s version here.

2021-06-02 07:04 UTC, thiagotnunes commented on google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerApiFuturesTest.java
> +    assertThat(SpannerApiFutures.getOrNull((ApiFuture<Object>) null)).isNull();
We had to add the explicit cast here, because of the Java 8 upgrade.

2021-06-02 13:38 UTC, suztomo commented
Memo:

Linkage Monitor complains about google-cloud-spanner-jdbc. This artifact is not in the LTS BOM.

```
SEVERE: Newly introduced problems:
(com.google.cloud:google-cloud-spanner:3.3.3-sp.2-SNAPSHOT) Interface com.google.cloud.spanner.connection.Connection's method getCommitResponse() is not found
  referenced from com.google.cloud.spanner.jdbc.JdbcConnection (com.google.cloud:google-cloud-spanner-jdbc:2.1.0)
(com.google.cloud:google-cloud-spanner:3.3.3-sp.2-SNAPSHOT) Interface com.google.cloud.spanner.connection.Connection's method setReturnCommitStats(boolean) is not found
  referenced from com.google.cloud.spanner.jdbc.JdbcConnection (com.google.cloud:google-cloud-spanner-jdbc:2.1.0)
(com.google.cloud:google-cloud-spanner:3.3.3-sp.2-SNAPSHOT) Interface com.google.cloud.spanner.connection.Connection's method isReturnCommitStats() is not found
  referenced from com.google.cloud.spanner.jdbc.JdbcConnection (com.google.cloud:google-cloud-spanner-jdbc:2.1.0)

com.google.cloud:google-cloud-spanner:3.3.3-sp.2-SNAPSHOT is at:
  com.google.cloud:google-cloud-spanner:3.3.3-sp.2-SNAPSHOT (compile)
com.google.cloud:google-cloud-spanner-jdbc:2.1.0 is at:
  com.google.cloud:google-cloud-spanner-jdbc:2.1.0 (compile)
```

This happens because the Linkage Monitor tries to get the latest Libraries BOM, which may not be compatible with the libraries in the LTS BOM.

The libraries BOM 20.0.0 (which will be used by the Beam release in LTS BOM) has `com.google.cloud:google-cloud-spanner-jdbc:2.0.0`

2021-06-02 14:53 UTC, suztomo commented
@thiagotnunes Thank you for the detailed notes.

> We had to remove the dependency on google-cloud-shared-dependencies

Was this also for the enforcer rule (upper-bound check)?

2021-06-02 23:44 UTC, thiagotnunes commented
@suztomo Yes, that was the reason for removing it

2021-06-07 18:34 UTC, elharo requested changes
I don't think you need to merge this. This is all for testing, not shipping.

2021-06-08 01:30 UTC, thiagotnunes commented
@elharo ok, but I guess we will need to do some modifications once we have the final LTS BOM, which could be based on this PR.

2021-06-08 01:30 UTC, closed without merging