docs(sample): relocate native image sample from old repo
googleapis/java-spanner pull request #1758
Opened 2022-03-18 20:35 UTC by mpeddada1

Relocating Spanner sample from [GoogleCloudPlatform/native-image-support-java](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/spanner-sample). 
This PR also adds an integration test that can be run as a native image.

Calling `mvn package -Pnative -DskipTests` builds the native image for the application and calling `mvn test -Pnative` runs the test as a native image. 

For more information: https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration.

2022-03-29 17:08 UTC, ansh0l approved these changes
LGTM. 

Minor nit: I think since the parent folder is named `samples`, we should call this one as `native-image` instead of `native-image-sample`

2022-04-26 19:10 UTC, mpeddada1 commented
Thank you @ansh0l! I've renamed this to `native-image`

2022-05-23 07:47 UTC, ansh0l commented
Closing since native image changes have been released with https://github.com/googleapis/java-spanner/pull/1878

2022-05-23 07:47 UTC, closed without merging

2022-05-26 10:36 UTC, ansh0l requested changes
@mpeddada1 : Are you looking to merge this PR? it has conflicts in its readme, please check.

2022-05-26 19:56 UTC, mpeddada1 commented
@ansh0l, thank you, I've resolved the merge conflict.

2022-06-01 17:25 UTC, mpeddada1 commented
All checks are now green.

2022-06-01 17:53 UTC, ansh0l reviewed
At a quick glance, looks alright. Please take a full review with @rajatbhatta

2022-06-01 17:53 UTC, ansh0l commented on samples/native-image/pom.xml
> +        <version>25.2.0</version>
QQ> AFAIK, currently, we get automated PRs for cloud bom version bumps. Would now there be 2 such PRs (one for regular samples/pom.xml, another for samples/native-image/pom.xml), or would both end up coming into 1 PR?

2022-06-02 11:10 UTC, rajatbhatta commented on samples/native-image/README.md
> +This is a sample application which uses the Cloud Spanner client libraries and demonstrates compatibility with Native Image native image compilation.
```suggestion
This is a sample application which uses the Cloud Spanner client libraries and demonstrates compatibility with Native Image compilation.
```

2022-06-02 11:12 UTC, mpeddada1 commented on samples/native-image/README.md
> +This is a sample application which uses the Cloud Spanner client libraries and demonstrates compatibility with Native Image native image compilation.
Good catch! Done.

2022-06-02 11:23 UTC, rajatbhatta approved these changes
LGTM.